//
//  ContentView.swift
//  Prod
//
//  Engineer screen — chip-list prompt builder + result history. Productionised
//  from the Playground: real backend (chat synthesize → generate → poll →
//  fetch) and disk-backed persistence so runs and chips survive launches.
//

import SwiftUI
import UIKit
import Api
import ProjectService

// MARK: - Models

struct Chip: Identifiable, Equatable, Codable {
    let id: UUID
    var text: String

    init(text: String) {
        self.id = UUID()
        self.text = text
    }
}

struct Run: Identifiable {
    enum State: Codable {
        case loading
        case loaded
        case failed
    }

    let id: UUID
    var chips: [Chip]
    var state: State
    /// Disk filename under `Documents/` (via ProjectService). Empty until loaded.
    var imageFilename: String
    /// Decoded image, cached after first read so the row doesn't re-decode
    /// every render. Nil while loading or failed.
    var image: UIImage?
    var liked: Bool
    /// Index into `gradientPalettes` — used as the shimmer/failure backdrop
    /// and the fallback if decoding fails.
    let paletteIndex: Int
    let createdAt: Date

    init(
        id: UUID = UUID(),
        chips: [Chip],
        state: State,
        imageFilename: String = "",
        image: UIImage? = nil,
        liked: Bool = false,
        paletteIndex: Int,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.chips = chips
        self.state = state
        self.imageFilename = imageFilename
        self.image = image
        self.liked = liked
        self.paletteIndex = paletteIndex
        self.createdAt = createdAt
    }
}

/// One batch as rendered in the RESULTS section. Grouping is derived from
/// `Run.createdAt` (rounded into a 2-second window) — runs that landed from
/// one Generate tap share a bucket. `id` just gives ForEach stable identity.
struct RunBatch: Identifiable {
    let id: UUID
    let createdAt: Date
    let runs: [Run]
}

struct PendingUndo: Identifiable {
    let id = UUID()
    let run: Run
    let index: Int
}

// MARK: - Persistence
//
// Source of truth is the disk via ProjectService. Each row is one PNG under
// `Documents/<runId>.png` with chips embedded as IPTC keywords, the joined
// prompt as IPTC Caption/Abstract, the model as TIFF Software, and the like
// state as IPTC StarRating. The editor's working chip set lives separately
// in UserDefaults because it's not a generation, just typing in progress.

private enum Store {
    private static let chipsKey = "engineerChips.v1"

    static func loadChips() -> [Chip] {
        guard let data = UserDefaults.standard.data(forKey: chipsKey),
              let chips = try? JSONDecoder().decode([Chip].self, from: data) else {
            return []
        }
        return chips
    }

    static func saveChips(_ chips: [Chip]) {
        guard let data = try? JSONEncoder().encode(chips) else { return }
        UserDefaults.standard.set(data, forKey: chipsKey)
    }

    /// Walks `Documents/` via ProjectService and reconstructs Runs from each
    /// PNG's embedded XMP (subject keywords → chips, rating → liked) plus the
    /// file's creation date. Newest first. No sidecar — the disk IS the index.
    static func loadRuns() -> [Run] {
        ProjectService.getAllGenerations()
            .filter { $0.pathExtension.lowercased() == "png" }
            .compactMap { url -> Run? in
                let filename = url.lastPathComponent
                guard let bytes = try? Data(contentsOf: url),
                      let img = UIImage(data: bytes) else {
                    return nil
                }
                let chipTexts = ProjectService.getSubject(filename) ?? []
                let liked = ProjectService.getLike(filename)
                let createdAt: Date = {
                    let attrs = try? FileManager.default.attributesOfItem(atPath: url.path)
                    return (attrs?[.creationDate] as? Date) ?? Date()
                }()
                let runId = UUID(uuidString: url.deletingPathExtension().lastPathComponent) ?? UUID()
                return Run(
                    id: runId,
                    chips: chipTexts.map { Chip(text: $0) },
                    state: .loaded,
                    imageFilename: filename,
                    image: img,
                    liked: liked,
                    paletteIndex: abs(filename.hashValue),
                    createdAt: createdAt
                )
            }
            .sorted { $0.createdAt > $1.createdAt }
    }

    /// Persists the generated bytes with chips embedded as IPTC keywords,
    /// joined prompt as Caption/Abstract, and the model name as TIFF Software.
    /// `model` is honest about which path produced this image — `"Flux2Pro"`
    /// in default mode, `"Flux2KleinI2I"` in cast mode.
    /// Returns the on-disk filename.
    @discardableResult
    static func saveRun(data: Data, runId: UUID, chips: [Chip], model: String = "Flux2Pro") -> String {
        let filename = "\(runId.uuidString).png"
        ProjectService.saveFile(
            data,
            named: filename,
            prompt: chips.map(\.text).joined(separator: ", "),
            model: model,
            subject: chips.map(\.text)
        )
        return filename
    }

    static func setLiked(filename: String, liked: Bool) {
        ProjectService.like(filename, liked)
    }

    /// ProjectService doesn't expose a delete primitive; resolve the URL
    /// through it so we share the same path convention, then unlink.
    static func deleteImage(filename: String) {
        guard !filename.isEmpty else { return }
        try? FileManager.default.removeItem(at: ProjectService.getUrl(for: filename))
    }
}

// MARK: - Image service (real backend)

enum ImageServiceError: LocalizedError {
    case requestFailed(String)
    case decodingFailed
    case taskFailed

    var errorDescription: String? {
        switch self {
        case .requestFailed(let s): return s
        case .decodingFailed: return "couldn't read result"
        case .taskFailed: return "generation failed"
        }
    }
}

final class ImageService: @unchecked Sendable {
    static let shared = ImageService()

    private var bearer: String = ""

    private init() {}

    static func configure(bearer: String) {
        shared.bearer = bearer
        ApiAPIConfiguration.shared.customHeaders["Authorization"] = "Bearer \(bearer)"
    }

    /// Cast mode: load both reference files from disk, base64-encode raw
    /// (iOS path per schema), and call Klein once. Caller is responsible for
    /// pre-synthesizing the prompt — every text path runs through synth.
    func castGenerate(
        prompt: String,
        characterFilename: String,
        targetFilename: String
    ) async throws -> (data: Data, serverFilename: String) {
        let characterURL = ProjectService.getUrl(for: characterFilename)
        let targetURL = ProjectService.getUrl(for: targetFilename)
        guard let characterData = try? Data(contentsOf: characterURL),
              let targetData = try? Data(contentsOf: targetURL) else {
            throw ImageServiceError.requestFailed("couldn't read cast reference bytes")
        }
        let id = UUID()
        let result = try await call(.typeFlux2KleinI2I(Flux2KleinI2I(
            comfyRequestId: "",
            file: "",
            image: characterData.base64EncodedString(),
            image2: targetData.base64EncodedString(),
            prompt: prompt,
            type: .flux2KleinI2I
        )), id: id)
        guard result.status == .completed else { throw ImageServiceError.taskFailed }
        guard case .typeFlux2KleinI2I(let k) = result.action else {
            throw ImageServiceError.decodingFailed
        }
        let data = try Self.decodeBase64(k.file)
        return (data, "\(id.uuidString).png")
    }

    /// Sends the user's idea to chat and returns one synthesized image prompt.
    /// Per-slot natural variation comes from the LLM's own temperature when N
    /// of these run in parallel against the same input. Runs on every Generate
    /// regardless of mode — Engineer treats chat synthesis as universal.
    func chatSynthesize(idea: String) async throws -> String {
        let userIdea = idea.isEmpty ? "Surprise me — generate something interesting." : idea
        let synthesizerRequest = """
            Make image prompt frame for Flux2. Reply with only the prompt, nothing else.
            Idea: \(userIdea)
            """
        let chatAction: ApiAction = .typeClaudeSonnet46(ClaudeSonnet46(
            messages: [ApiChatMessage(content: synthesizerRequest, role: .user)],
            type: .claudesonnet46
        ))
        let response = try await call(chatAction, id: UUID())
        if case .typeClaudeSonnet46(let chat) = response.action,
           let last = chat.messages.last(where: { $0.role == .assistant })?.content,
           !last.isEmpty {
            return last
        }
        return userIdea
    }

    /// Single call → base64-decode. The result `file` is image bytes encoded
    /// inline as base64 (optionally with a `data:image/...;base64,` prefix),
    /// so the request returns the finished image in one round-trip. Caller
    /// supplies a pre-synthesized prompt.
    func generate(prompt: String) async throws -> (Data, String) {
        let id = UUID()
        let result = try await call(.typeFlux2Pro(Flux2Pro(
            falRequestId: "", file: "", prompt: prompt, type: .flux2Pro
        )), id: id)
        guard result.status == .completed else { throw ImageServiceError.taskFailed }
        guard case .typeFlux2Pro(let fp) = result.action else {
            throw ImageServiceError.decodingFailed
        }
        let data = try Self.decodeBase64(fp.file)
        return (data, "\(id.uuidString).png")
    }

    private func call(_ action: ApiAction, id: UUID) async throws -> API {
        let req = API(
            action: action,
            credit: 0,
            id: id,
            status: .pending,
            userId: ""
        )
        do {
            return try await ApiHandlerAPI.apiHandler(API: req)
        } catch let ErrorResponse.error(status, data, _, underlying) {
            let body = data.flatMap { String(data: $0, encoding: .utf8) } ?? ""
            let ns = underlying as NSError
            let msg = status > 0
                ? "HTTP \(status) — \(body.prefix(120))"
                : "\(ns.domain) \(ns.code): \(ns.localizedDescription)"
            throw ImageServiceError.requestFailed(msg)
        }
    }

    /// Decodes the `file` field returned by the model (base64, optionally
    /// prefixed with a `data:image/...;base64,` URI scheme) into raw bytes.
    private static func decodeBase64(_ encoded: String) throws -> Data {
        let stripped: String
        if let comma = encoded.firstIndex(of: ",") {
            stripped = String(encoded[encoded.index(after: comma)...])
        } else {
            stripped = encoded
        }
        guard let data = Data(base64Encoded: stripped, options: [.ignoreUnknownCharacters]) else {
            throw ImageServiceError.decodingFailed
        }
        return data
    }
}

// MARK: - ContentView

public struct ContentView: View {
    @State private var chips: [Chip]
    @State private var runs: [Run]
    @State private var editingId: Chip.ID?
    @State private var editingText: String = ""
    @State private var newChipText: String = ""
    @State private var addingNew = false
    @State private var editorVisible = true
    @State private var pendingUndos: [PendingUndo] = []
    /// In-flight generation tasks, keyed by run id. Cancelled when the row
    /// is removed so we don't burn API calls on results no one will see.
    @State private var inflight: [Run.ID: Task<Void, Never>] = [:]
    @State private var showLikedOnly = false

    @FocusState private var focusedField: Field?
    enum Field: Hashable {
        case edit(UUID)
        case add
    }

    public init(bearer: String) {
        ImageService.configure(bearer: bearer)
        _chips = State(initialValue: Store.loadChips())
        _runs = State(initialValue: Store.loadRuns())
    }

    private let presets = ["Cinematic", "Neon", "Moody", "Pastel", "Film", "Surreal", "Vintage", "Dreamy"]
    private let maxChips = 20
    private let maxRuns = 30
    private let parallelRuns = 3
    /// Credits charged per row generated (1 chat + 1 image generation). One
    /// Generate tap fans out to `parallelRuns × creditPerRun` credits total.
    private let creditPerRun = 1
    private var costPerGenerate: Int { creditPerRun * parallelRuns }
    private var atCap: Bool { chips.count >= maxChips }

    private static let lightHaptic = UIImpactFeedbackGenerator(style: .soft)
    private static let mediumHaptic = UIImpactFeedbackGenerator(style: .light)
    private func tap(_ feedback: UIImpactFeedbackGenerator = ContentView.lightHaptic) {
        feedback.impactOccurred()
    }

    public var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            RadialGradient(
                colors: [Color(red: 0.42, green: 0.10, blue: 0.55).opacity(0.35), .clear],
                center: .init(x: 0.18, y: 0.05), startRadius: 0, endRadius: 420
            )
            .ignoresSafeArea()
            RadialGradient(
                colors: [Color(red: 0.95, green: 0.30, blue: 0.55).opacity(0.22), .clear],
                center: .init(x: 0.92, y: 0.08), startRadius: 0, endRadius: 320
            )
            .ignoresSafeArea()

            VStack(spacing: 0) {
                header
                ScrollViewReader { proxy in
                    ZStack(alignment: .top) {
                        ScrollView {
                            VStack(alignment: .leading, spacing: 20) {
                                promptHeader
                                    .id("editorTop")
                                chipFlow
                                    .padding(.horizontal, 16)
                                    .onScrollVisibilityChange { visible in
                                        withAnimation(.easeInOut(duration: 0.2)) {
                                            editorVisible = visible
                                        }
                                    }

                                sectionLabel("PRESETS")
                                presetRail

                                if !runs.isEmpty {
                                    resultsHeader
                                    resultsSection
                                }
                            }
                            .padding(.vertical, 16)
                        }
                        .scrollIndicators(.hidden)
                        .scrollDismissesKeyboard(.interactively)

                        if !editorVisible && !chips.isEmpty {
                            backToEditorPill(proxy: proxy)
                                .padding(.top, 8)
                                .transition(.move(edge: .top).combined(with: .opacity))
                                .zIndex(1)
                        }
                    }
                }

                generateButton
                    .padding(.horizontal, 22)
                    .padding(.bottom, 14)
            }

            if !pendingUndos.isEmpty {
                VStack {
                    Spacer()
                    undoToast
                        .padding(.horizontal, 22)
                        .padding(.bottom, 88)
                        .transition(.move(edge: .bottom).combined(with: .opacity))
                }
                .allowsHitTesting(true)
            }
        }
        .preferredColorScheme(.dark)
        .toolbar {
            ToolbarItemGroup(placement: .keyboard) {
                Spacer()
                Button("Done") { dismissAll() }
                    .foregroundStyle(Color(red: 1.0, green: 0.30, blue: 0.65))
                    .font(.system(size: 15, weight: .semibold))
            }
        }
        .onChange(of: chips) { _, new in Store.saveChips(new) }
    }

    // MARK: Header

    private var header: some View {
        HStack {
            HStack(spacing: 8) {
                Circle()
                    .fill(LinearGradient(
                        colors: [Color(red: 0.55, green: 0.20, blue: 1.0),
                                 Color(red: 1.0, green: 0.30, blue: 0.65)],
                        startPoint: .leading, endPoint: .trailing))
                    .frame(width: 8, height: 8)
                Text("ENGINEER")
                    .font(.system(size: 12, weight: .heavy))
                    .tracking(2.8)
                    .foregroundStyle(.white.opacity(0.85))
            }
            Spacer()
        }
        .padding(.horizontal, 22)
        .padding(.top, 8)
        .padding(.bottom, 14)
    }

    /// Floating status reader shown when the editor has scrolled out of view.
    /// Displays the live joined prompt (truncated) so the user can confirm
    /// restores from history without scrolling, and tap to spring back to
    /// the editor when they want to edit.
    private func backToEditorPill(proxy: ScrollViewProxy) -> some View {
        Button {
            UIImpactFeedbackGenerator(style: .soft).impactOccurred()
            withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
                proxy.scrollTo("editorTop", anchor: .top)
            }
        } label: {
            HStack(spacing: 8) {
                Text(chips.map(\.text).joined(separator: " · "))
                    .font(.system(size: 12, weight: .semibold))
                    .lineLimit(1)
                    .truncationMode(.tail)
                Image(systemName: "arrow.up")
                    .font(.system(size: 10, weight: .heavy))
                    .opacity(0.85)
            }
            .foregroundStyle(.white)
            .padding(.horizontal, 14)
            .padding(.vertical, 8)
            .frame(maxWidth: 320)
            .background(
                Capsule().fill(LinearGradient(
                    colors: [Color(red: 0.55, green: 0.20, blue: 1.0).opacity(0.92),
                             Color(red: 1.0, green: 0.30, blue: 0.65).opacity(0.92)],
                    startPoint: .leading, endPoint: .trailing
                ))
            )
            .overlay(Capsule().strokeBorder(.white.opacity(0.3), lineWidth: 0.7))
            .shadow(color: Color(red: 0.95, green: 0.30, blue: 0.65).opacity(0.35), radius: 12, y: 4)
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Scroll back to editor. Current prompt: \(chips.map(\.text).joined(separator: ", "))")
    }

    /// Transient toast for undoing the last row removal. Auto-dismisses
    /// after 3 seconds — long enough to catch a mistake, short enough not
    /// to clutter the screen.
    private var undoToast: some View {
        HStack(spacing: 12) {
            Image(systemName: "trash")
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(.white.opacity(0.7))
            Text(pendingUndos.count > 1
                 ? "\(pendingUndos.count) results removed"
                 : "Result removed")
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(.white)
            Spacer()
            Button {
                undoRemove()
            } label: {
                Text("Undo")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(Color(red: 1.0, green: 0.30, blue: 0.65))
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Undo remove")
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(Color.black.opacity(0.7))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(.white.opacity(0.15), lineWidth: 0.5)
        )
        .shadow(color: .black.opacity(0.4), radius: 16, y: 6)
    }

    /// PROMPT section header with an inline CLEAR affordance on the right.
    private var promptHeader: some View {
        HStack(spacing: 0) {
            sectionLabel("PROMPT")
            Spacer()
            if !chips.isEmpty {
                Button {
                    clearAll()
                } label: {
                    Text("CLEAR")
                        .font(.system(size: 10, weight: .heavy))
                        .tracking(1.5)
                        .foregroundStyle(.white.opacity(0.5))
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .background(Capsule().fill(.white.opacity(0.05)))
                        .overlay(Capsule().strokeBorder(.white.opacity(0.12), lineWidth: 0.5))
                }
                .buttonStyle(.plain)
                .padding(.trailing, 22)
                .accessibilityLabel("Clear all phrases")
            }
        }
    }

    private func sectionLabel(_ text: String) -> some View {
        Text(text)
            .font(.system(size: 10, weight: .heavy))
            .tracking(2)
            .foregroundStyle(.white.opacity(0.45))
            .padding(.horizontal, 22)
    }

    // MARK: Chip flow

    private var chipFlow: some View {
        VStack(alignment: .leading, spacing: 0) {
            ChipFlowLayout(spacing: 8, lineSpacing: 8) {
                ForEach(chips) { chip in
                    chipView(chip)
                }
                addChipView
            }
            if chips.isEmpty && !addingNew {
                Text("tap + to begin engineering your prompt")
                    .font(.system(size: 12, weight: .medium))
                    .foregroundStyle(.white.opacity(0.35))
                    .padding(.top, 10)
            }
        }
    }

    @ViewBuilder
    private func chipView(_ chip: Chip) -> some View {
        if editingId == chip.id {
            inlineEditor(for: chip)
        } else {
            HStack(spacing: 6) {
                Text(chip.text)
                    .font(.system(size: 14, weight: .medium))
                    .foregroundStyle(.white.opacity(0.92))
                    .lineLimit(1)
                    .truncationMode(.tail)
                    .frame(maxWidth: 300, alignment: .leading)
                    .onTapGesture {
                        beginEdit(chip)
                    }
                    .accessibilityHint("Double-tap to edit")
                Button {
                    remove(chip)
                } label: {
                    Image(systemName: "xmark")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(.white.opacity(0.6))
                        .frame(width: 22, height: 22)
                        .background(Circle().fill(.white.opacity(0.10)))
                }
                .buttonStyle(.plain)
                .accessibilityLabel("Remove \(chip.text)")
            }
            .padding(.leading, 14)
            .padding(.trailing, 5)
            .padding(.vertical, 7)
            .background(Capsule().fill(Color.white.opacity(0.08)))
            .overlay(Capsule().strokeBorder(.white.opacity(0.12), lineWidth: 0.5))
            .transition(.scale(scale: 0.85).combined(with: .opacity))
        }
    }

    private func inlineEditor(for chip: Chip) -> some View {
        AutoChipField(
            text: $editingText,
            placeholder: "",
            maxWidth: 240,
            submitLabel: .done,
            onSubmit: { commitEdit() },
            focus: $focusedField,
            focusValue: .edit(chip.id)
        )
        .padding(.horizontal, 14)
        .padding(.vertical, 7)
        .background(Capsule().fill(Color.white.opacity(0.14)))
        .overlay(Capsule().strokeBorder(.white.opacity(0.35), lineWidth: 0.7))
    }

    @ViewBuilder
    private var addChipView: some View {
        if atCap && !addingNew {
            EmptyView()
        } else {
            addChipBody
        }
    }

    private var addChipBody: some View {
        Group {
            if addingNew {
                HStack(spacing: 4) {
                    Image(systemName: "plus")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(.white.opacity(0.6))
                    AutoChipField(
                        text: $newChipText,
                        placeholder: "phrase",
                        maxWidth: 240,
                        submitLabel: .next,
                        onSubmit: { commitAndContinueAdd() },
                        focus: $focusedField,
                        focusValue: .add
                    )
                }
                .padding(.horizontal, 14)
                .padding(.vertical, 7)
                .background(Capsule().fill(Color.white.opacity(0.14)))
                .overlay(Capsule().strokeBorder(.white.opacity(0.35), lineWidth: 0.7))
            } else {
                Button {
                    beginAdd()
                } label: {
                    HStack(spacing: 4) {
                        Image(systemName: "plus")
                            .font(.system(size: 10, weight: .bold))
                        Text("add")
                            .font(.system(size: 13, weight: .semibold))
                    }
                    .foregroundStyle(.white.opacity(0.55))
                    .padding(.horizontal, 14)
                    .padding(.vertical, 8)
                    .background(Capsule().fill(Color.white.opacity(0.04)))
                    .overlay(
                        Capsule().strokeBorder(.white.opacity(0.18),
                                               style: StrokeStyle(lineWidth: 0.7, dash: [3, 4]))
                    )
                }
                .buttonStyle(.plain)
                .accessibilityLabel("Add phrase")
            }
        }
    }

    // MARK: Preset rail

    private var presetRail: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 8) {
                ForEach(presets, id: \.self) { p in
                    Button {
                        insertPreset(p)
                    } label: {
                        Text(p)
                            .font(.system(size: 13, weight: .semibold))
                            .foregroundStyle(.white.opacity(0.85))
                            .padding(.horizontal, 14)
                            .padding(.vertical, 8)
                            .background(Capsule().fill(.white.opacity(0.06)))
                            .overlay(Capsule().strokeBorder(.white.opacity(0.12), lineWidth: 0.5))
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.horizontal, 22)
        }
    }

    // MARK: Results

    /// RESULTS row with the LIKED filter chip on the right. Filter is hidden
    /// when no liked rows exist (nothing to surface, no point in the affordance).
    private var resultsHeader: some View {
        HStack(spacing: 0) {
            sectionLabel("RESULTS")
            Spacer()
            if runs.contains(where: { $0.liked }) {
                likedFilterChip
                    .padding(.trailing, 22)
            }
        }
    }

    private var likedFilterChip: some View {
        Button {
            UIImpactFeedbackGenerator(style: .soft).impactOccurred()
            withAnimation(.easeInOut(duration: 0.2)) {
                showLikedOnly.toggle()
            }
        } label: {
            HStack(spacing: 4) {
                Image(systemName: showLikedOnly ? "heart.fill" : "heart")
                    .font(.system(size: 9, weight: .heavy))
                Text("LIKED")
                    .font(.system(size: 10, weight: .heavy))
                    .tracking(1.5)
            }
            .foregroundStyle(showLikedOnly
                ? Color(red: 1.0, green: 0.30, blue: 0.65)
                : .white.opacity(0.5))
            .padding(.horizontal, 10)
            .padding(.vertical, 4)
            .background(Capsule().fill(showLikedOnly
                ? Color(red: 1.0, green: 0.30, blue: 0.65).opacity(0.15)
                : .white.opacity(0.05)))
            .overlay(Capsule().strokeBorder(showLikedOnly
                ? Color(red: 1.0, green: 0.30, blue: 0.65).opacity(0.5)
                : .white.opacity(0.12), lineWidth: 0.5))
        }
        .buttonStyle(.plain)
        .accessibilityLabel(showLikedOnly ? "Show all results" : "Show only liked results")
    }

    private var resultsSection: some View {
        let filtered = showLikedOnly ? runs.filter(\.liked) : runs
        let batches = batched(filtered)
        return VStack(alignment: .leading, spacing: 16) {
            ForEach(batches) { batch in
                VStack(alignment: .leading, spacing: 10) {
                    batchHeader(batch.createdAt)
                    ForEach(batch.runs) { run in
                        resultRow(run)
                    }
                }
            }
        }
    }

    /// "GENERATED · 2m ago" caption above each batch of rows. Snapshot at
    /// render time — relative string ages with each scroll re-render, which
    /// is good enough for human time perception without a 1s timer.
    private func batchHeader(_ date: Date) -> some View {
        HStack(spacing: 6) {
            Text("GENERATED")
                .font(.system(size: 9, weight: .heavy))
                .tracking(1.2)
            Text("·")
                .font(.system(size: 9, weight: .heavy))
            Text(Self.relativeString(date))
                .font(.system(size: 9, weight: .heavy))
                .tracking(0.8)
        }
        .foregroundStyle(.white.opacity(0.4))
        .padding(.horizontal, 22)
    }

    /// Groups consecutive runs into 2-second `createdAt` buckets — runs from
    /// one Generate tap share a bucket because they're stamped within ms of
    /// each other. After reload, the file's creation date drives bucketing
    /// just as well as the in-memory timestamp.
    private func batched(_ runs: [Run]) -> [RunBatch] {
        var result: [RunBatch] = []
        var current: [Run] = []
        var currentKey: TimeInterval = -1
        let bucketSeconds: TimeInterval = 2

        for run in runs {
            let key = floor(run.createdAt.timeIntervalSince1970 / bucketSeconds)
            if !current.isEmpty, key == currentKey {
                current.append(run)
            } else {
                if let first = current.first {
                    result.append(RunBatch(id: first.id, createdAt: first.createdAt, runs: current))
                }
                current = [run]
                currentKey = key
            }
        }
        if let first = current.first {
            result.append(RunBatch(id: first.id, createdAt: first.createdAt, runs: current))
        }
        return result
    }

    private static let relativeFormatter: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f
    }()

    private static func relativeString(_ date: Date) -> String {
        relativeFormatter.localizedString(for: date, relativeTo: Date())
    }

    private func resultRow(_ run: Run) -> some View {
        let active = isActive(run)
        return Button {
            restore(run)
        } label: {
            HStack(alignment: .top, spacing: 12) {
                thumbnail(run)
                VStack(alignment: .leading, spacing: 6) {
                    Text(joinedPrompt(for: run))
                        .font(.system(size: 13, weight: .medium))
                        .foregroundStyle(.white.opacity(0.82))
                        .lineLimit(3)
                        .truncationMode(.tail)
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Text("\(run.chips.count) \(run.chips.count == 1 ? "phrase" : "phrases")")
                        .font(.system(size: 9, weight: .heavy))
                        .tracking(1.2)
                        .foregroundStyle(.white.opacity(0.4))
                }
                VStack(spacing: 8) {
                    if run.state == .failed {
                        retryButton(run)
                    } else {
                        heartButton(run)
                    }
                    removeButton(run)
                }
            }
            .padding(12)
            .background(
                RoundedRectangle(cornerRadius: 16, style: .continuous)
                    .fill(Color.white.opacity(active ? 0.08 : 0.04))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 16, style: .continuous)
                    .strokeBorder(
                        active
                            ? AnyShapeStyle(LinearGradient(
                                colors: [Color(red: 0.55, green: 0.20, blue: 1.0),
                                         Color(red: 1.0, green: 0.30, blue: 0.65)],
                                startPoint: .leading, endPoint: .trailing))
                            : AnyShapeStyle(Color.white.opacity(0.08)),
                        lineWidth: active ? 1.2 : 0.5
                    )
            )
        }
        .buttonStyle(RowPressStyle())
        .padding(.horizontal, 22)
        .accessibilityLabel("Restore prompt: \(run.chips.map(\.text).joined(separator: ", "))")
        .transition(.scale(scale: 0.95).combined(with: .opacity))
    }

    private func heartButton(_ run: Run) -> some View {
        Button {
            toggleLike(run)
        } label: {
            Image(systemName: run.liked ? "heart.fill" : "heart")
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(run.liked
                    ? Color(red: 1.0, green: 0.30, blue: 0.65)
                    : .white.opacity(0.55))
                .frame(width: 28, height: 28)
                .background(Circle().fill(.white.opacity(0.06)))
        }
        .buttonStyle(.plain)
        .accessibilityLabel(run.liked ? "Unlike result" : "Like result")
    }

    private func retryButton(_ run: Run) -> some View {
        Button {
            retry(run)
        } label: {
            Image(systemName: "arrow.clockwise")
                .font(.system(size: 11, weight: .bold))
                .foregroundStyle(.white.opacity(0.8))
                .frame(width: 28, height: 28)
                .background(Circle().fill(.white.opacity(0.10)))
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Retry generation")
    }

    private func removeButton(_ run: Run) -> some View {
        Button {
            removeRun(run)
        } label: {
            Image(systemName: "xmark")
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(.white.opacity(0.5))
                .frame(width: 28, height: 28)
                .background(Circle().fill(.white.opacity(0.06)))
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Remove result")
    }

    private func thumbnail(_ run: Run) -> some View {
        let palette = Self.gradientPalettes[run.paletteIndex % Self.gradientPalettes.count]
        return RoundedRectangle(cornerRadius: 10, style: .continuous)
            .fill(LinearGradient(
                colors: palette,
                startPoint: .topLeading, endPoint: .bottomTrailing
            ))
            .frame(width: 96, height: 96)
            .overlay {
                switch run.state {
                case .loading:
                    ShimmerOverlay()
                        .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
                case .loaded:
                    if let img = run.image {
                        Image(uiImage: img)
                            .resizable()
                            .interpolation(.high)
                            .aspectRatio(contentMode: .fill)
                            .frame(width: 96, height: 96)
                            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
                    }
                case .failed:
                    ZStack {
                        Color.black.opacity(0.45)
                        Image(systemName: "exclamationmark.triangle.fill")
                            .font(.system(size: 22, weight: .semibold))
                            .foregroundStyle(.white.opacity(0.9))
                    }
                    .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
                }
            }
    }

    private static let gradientPalettes: [[Color]] = [
        [Color(red: 1.00, green: 0.50, blue: 0.30), Color(red: 0.80, green: 0.20, blue: 0.50)],
        [Color(red: 0.30, green: 0.50, blue: 1.00), Color(red: 0.60, green: 0.20, blue: 0.90)],
        [Color(red: 0.95, green: 0.60, blue: 0.20), Color(red: 0.70, green: 0.30, blue: 0.70)],
        [Color(red: 0.20, green: 0.60, blue: 0.70), Color(red: 0.50, green: 0.80, blue: 0.50)],
        [Color(red: 0.60, green: 0.20, blue: 0.40), Color(red: 0.90, green: 0.40, blue: 0.60)],
        [Color(red: 0.15, green: 0.25, blue: 0.45), Color(red: 0.70, green: 0.45, blue: 0.65)],
    ]

    // MARK: Generate

    private var generateButton: some View {
        Button {
            generate()
        } label: {
            HStack(spacing: 10) {
                Image(systemName: "sparkles")
                    .font(.system(size: 17, weight: .bold))
                VStack(spacing: 1) {
                    Text("Generate")
                        .font(.system(size: 17, weight: .bold))
                        .tracking(0.5)
                    Text("\(costPerGenerate) credits")
                        .font(.system(size: 9, weight: .semibold))
                        .tracking(0.4)
                        .opacity(0.7)
                }
            }
            .foregroundStyle(.white)
            .frame(maxWidth: .infinity)
            .frame(height: 58)
            .background {
                ZStack {
                    LinearGradient(
                        colors: [Color(red: 0.55, green: 0.20, blue: 1.0),
                                 Color(red: 1.0, green: 0.30, blue: 0.65)],
                        startPoint: .leading, endPoint: .trailing
                    )
                    LinearGradient(
                        colors: [.white.opacity(0.35), .clear],
                        startPoint: .top, endPoint: .center
                    ).blendMode(.plusLighter).opacity(0.5)
                }
            }
            .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: 20, style: .continuous)
                    .strokeBorder(.white.opacity(0.5), lineWidth: 0.7)
            }
            .shadow(color: Color(red: 0.95, green: 0.30, blue: 0.65).opacity(0.45), radius: 24, y: 10)
            .opacity(chips.isEmpty ? 0.5 : 1.0)
        }
        .buttonStyle(.plain)
        .disabled(chips.isEmpty)
    }

    // MARK: Actions

    private func beginEdit(_ chip: Chip) {
        commitEdit()
        commitAdd()
        tap()
        editingId = chip.id
        editingText = chip.text
        DispatchQueue.main.async {
            focusedField = .edit(chip.id)
        }
    }

    private func commitEdit() {
        guard let id = editingId else { return }
        let trimmed = editingText.trimmingCharacters(in: .whitespaces)
        withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
            if trimmed.isEmpty {
                chips.removeAll { $0.id == id }
            } else if let idx = chips.firstIndex(where: { $0.id == id }) {
                chips[idx].text = trimmed
            }
            editingId = nil
            editingText = ""
        }
    }

    private func remove(_ chip: Chip) {
        tap(ContentView.mediumHaptic)
        withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
            chips.removeAll { $0.id == chip.id }
        }
    }

    private func beginAdd() {
        commitEdit()
        tap()
        addingNew = true
        newChipText = ""
        DispatchQueue.main.async {
            focusedField = .add
        }
    }

    private func commitAndContinueAdd() {
        guard addingNew else { return }
        let trimmed = newChipText.trimmingCharacters(in: .whitespaces)
        if trimmed.isEmpty {
            addingNew = false
            newChipText = ""
            focusedField = nil
            return
        }
        if atCap {
            UINotificationFeedbackGenerator().notificationOccurred(.warning)
            return
        }
        tap()
        withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
            chips.append(Chip(text: trimmed))
            newChipText = ""
        }
        DispatchQueue.main.async {
            focusedField = .add
        }
    }

    private func commitAdd() {
        guard addingNew else { return }
        let trimmed = newChipText.trimmingCharacters(in: .whitespaces)
        withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
            if !trimmed.isEmpty && !atCap {
                chips.append(Chip(text: trimmed))
            }
            addingNew = false
            newChipText = ""
        }
    }

    private func insertPreset(_ name: String) {
        commitEdit()
        commitAdd()
        guard !atCap else {
            UINotificationFeedbackGenerator().notificationOccurred(.warning)
            return
        }
        tap()
        withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
            chips.append(Chip(text: name.lowercased()))
        }
    }

    private func dismissAll() {
        commitEdit()
        commitAdd()
        focusedField = nil
    }

    private func clearAll() {
        dismissAll()
        UIImpactFeedbackGenerator(style: .light).impactOccurred()
        withAnimation(.spring(response: 0.3, dampingFraction: 0.85)) {
            chips.removeAll()
        }
    }

    /// Fans out `parallelRuns` real synthesizes per Generate tap. Each row
    /// appears shimmering, then resolves via the live chat→generate pipeline.
    /// Per-row Tasks are tracked so removeRun can cancel them.
    private func generate() {
        guard !chips.isEmpty else { return }
        dismissAll()
        tap()
        let snapshot = chips.map { Chip(text: $0.text) }
        let idea = snapshot.map(\.text).joined(separator: ", ")
        let createdAt = Date()
        let new = (0..<parallelRuns).map { _ in
            Run(
                chips: snapshot.map { Chip(text: $0.text) },
                state: .loading,
                paletteIndex: Int.random(in: 0..<Self.gradientPalettes.count),
                createdAt: createdAt
            )
        }
        withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
            runs.insert(contentsOf: new, at: 0)
            trimHistory()
        }
        for run in new {
            resolveReal(runId: run.id, idea: idea)
        }
    }

    private func retry(_ run: Run) {
        guard let idx = runs.firstIndex(where: { $0.id == run.id }) else { return }
        UIImpactFeedbackGenerator(style: .soft).impactOccurred()
        let idea = run.chips.map(\.text).joined(separator: ", ")
        withAnimation(.easeOut(duration: 0.2)) {
            runs[idx].state = .loading
        }
        resolveReal(runId: run.id, idea: idea)
    }

    /// Live API resolution for a single row. Every Generate goes through
    /// chat synthesis first; only the downstream call (Klein vs Flux2Pro)
    /// depends on whether `CharacterCast` is set. Persists bytes via
    /// ProjectService with an honest model name. Cancellation (via removeRun)
    /// propagates through Task.checkCancellation so we don't burn API calls.
    private func resolveReal(runId: Run.ID, idea: String) {
        let task = Task { @MainActor in
            defer { inflight.removeValue(forKey: runId) }
            do {
                let synthesized = try await ImageService.shared.chatSynthesize(idea: idea)
                try Task.checkCancellation()
                let data: Data
                let modelName: String
                if let (character, target) = ProjectService.getCharacterCast() {
                    (data, _) = try await ImageService.shared.castGenerate(
                        prompt: synthesized,
                        characterFilename: character,
                        targetFilename: target
                    )
                    modelName = "Flux2KleinI2I"
                } else {
                    (data, _) = try await ImageService.shared.generate(prompt: synthesized)
                    modelName = "Flux2Pro"
                }
                try Task.checkCancellation()
                guard let idx = runs.firstIndex(where: { $0.id == runId }) else { return }
                guard let img = UIImage(data: data) else { throw ImageServiceError.decodingFailed }
                let filename = Store.saveRun(data: data, runId: runId, chips: runs[idx].chips, model: modelName)
                // If the user toggled the heart while we were generating,
                // the in-memory `liked` flag is already true but the file
                // wasn't created yet — flush it now.
                if runs[idx].liked {
                    Store.setLiked(filename: filename, liked: true)
                }
                withAnimation(.easeOut(duration: 0.25)) {
                    runs[idx].state = .loaded
                    runs[idx].imageFilename = filename
                    runs[idx].image = img
                }
                UIImpactFeedbackGenerator(style: .soft).impactOccurred()
            } catch is CancellationError {
                // Row was removed before generation finished — nothing to do.
            } catch {
                guard let idx = runs.firstIndex(where: { $0.id == runId }) else { return }
                withAnimation(.easeOut(duration: 0.25)) {
                    runs[idx].state = .failed
                }
                UINotificationFeedbackGenerator().notificationOccurred(.error)
            }
        }
        inflight[runId] = task
    }

    /// Tap a past run to replace the editor with its prompt. Fresh chip IDs
    /// avoid collisions with the row that's still rendering the snapshot.
    private func restore(_ run: Run) {
        dismissAll()
        tap()
        withAnimation(.spring(response: 0.3, dampingFraction: 0.85)) {
            chips = run.chips.map { Chip(text: $0.text) }
        }
    }

    private func removeRun(_ run: Run) {
        guard let idx = runs.firstIndex(where: { $0.id == run.id }) else { return }
        UIImpactFeedbackGenerator(style: .light).impactOccurred()
        // Cancel any in-flight generation so we don't pay for unwanted bytes.
        inflight[run.id]?.cancel()
        inflight.removeValue(forKey: run.id)
        let undo = PendingUndo(run: runs[idx], index: idx)
        withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
            runs.remove(at: idx)
            pendingUndos.append(undo)
        }
        Task { @MainActor in
            try? await Task.sleep(for: .seconds(3))
            // If the user didn't undo, delete the disk bytes for real and
            // drop the entry from the undo stack.
            if pendingUndos.contains(where: { $0.id == undo.id }) {
                Store.deleteImage(filename: undo.run.imageFilename)
                withAnimation(.easeOut(duration: 0.2)) {
                    pendingUndos.removeAll { $0.id == undo.id }
                }
            }
        }
    }

    /// LIFO undo — restores the most recent removal first.
    private func undoRemove() {
        guard let undo = pendingUndos.last else { return }
        UIImpactFeedbackGenerator(style: .soft).impactOccurred()
        let insertAt = min(undo.index, runs.count)
        withAnimation(.spring(response: 0.3, dampingFraction: 0.85)) {
            runs.insert(undo.run, at: insertAt)
            pendingUndos.removeAll { $0.id == undo.id }
        }
    }

    private func toggleLike(_ run: Run) {
        guard let idx = runs.firstIndex(where: { $0.id == run.id }) else { return }
        UIImpactFeedbackGenerator(style: .soft).impactOccurred()
        withAnimation(.spring(response: 0.25, dampingFraction: 0.7)) {
            runs[idx].liked.toggle()
        }
        // Flush to the embedded IPTC rating, but only once the file exists.
        // For still-loading rows, resolveReal mirrors the like at save time.
        if runs[idx].state == .loaded, !runs[idx].imageFilename.isEmpty {
            Store.setLiked(filename: runs[idx].imageFilename, liked: runs[idx].liked)
        }
    }

    /// Trims to `maxRuns`, evicting unliked rows from the tail first so the
    /// user's keepers survive past the cap.
    private func trimHistory() {
        var overflow = runs.count - maxRuns
        guard overflow > 0 else { return }
        var i = runs.count - 1
        while overflow > 0 && i >= 0 {
            if !runs[i].liked {
                let dropped = runs.remove(at: i)
                Store.deleteImage(filename: dropped.imageFilename)
                overflow -= 1
            }
            i -= 1
        }
        if runs.count > maxRuns {
            let oldestExcess = runs.count - maxRuns
            for r in runs.suffix(oldestExcess) {
                Store.deleteImage(filename: r.imageFilename)
            }
            runs.removeLast(oldestExcess)
        }
    }

    private func isActive(_ run: Run) -> Bool {
        run.chips.map(\.text) == chips.map(\.text)
    }

    private func joinedPrompt(for run: Run) -> String {
        run.chips.map(\.text).joined(separator: " · ")
    }
}

// MARK: - AutoChipField

private struct AutoChipField: View {
    @Binding var text: String
    var placeholder: String
    var maxWidth: CGFloat
    var font: Font = .system(size: 14, weight: .medium)
    var submitLabel: SubmitLabel = .done
    var onSubmit: () -> Void
    @FocusState.Binding var focus: ContentView.Field?
    var focusValue: ContentView.Field

    @State private var measuredWidth: CGFloat = 70

    var body: some View {
        TextField(
            "",
            text: $text,
            prompt: Text(placeholder).foregroundColor(.white.opacity(0.35))
        )
        .focused($focus, equals: focusValue)
        .font(font)
        .foregroundStyle(.white)
        .tint(.white)
        .submitLabel(submitLabel)
        .onSubmit(onSubmit)
        .frame(width: measuredWidth)
        .background(measuringMirror)
        .onPreferenceChange(ChipWidthKey.self) { w in
            measuredWidth = min(max(60, w + 4), maxWidth)
        }
    }

    private var measuringMirror: some View {
        Text(text.isEmpty ? placeholder : text)
            .font(font)
            .lineLimit(1)
            .fixedSize()
            .background(
                GeometryReader { geo in
                    Color.clear
                        .preference(key: ChipWidthKey.self, value: geo.size.width)
                }
            )
            .opacity(0)
    }
}

private struct ChipWidthKey: PreferenceKey {
    static let defaultValue: CGFloat = 70
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) {
        value = nextValue()
    }
}

// MARK: - FlowLayout

struct ChipFlowLayout: Layout {
    var spacing: CGFloat = 8
    var lineSpacing: CGFloat = 8

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) -> CGSize {
        let maxWidth = proposal.width ?? .infinity
        var x: CGFloat = 0
        var y: CGFloat = 0
        var lineHeight: CGFloat = 0
        var maxLineWidth: CGFloat = 0

        for sub in subviews {
            let size = sub.sizeThatFits(.unspecified)
            if x + size.width > maxWidth, x > 0 {
                maxLineWidth = max(maxLineWidth, x - spacing)
                x = 0
                y += lineHeight + lineSpacing
                lineHeight = 0
            }
            x += size.width + spacing
            lineHeight = max(lineHeight, size.height)
        }
        maxLineWidth = max(maxLineWidth, x - spacing)
        return CGSize(width: maxLineWidth, height: y + lineHeight)
    }

    func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) {
        let maxWidth = bounds.width
        var x: CGFloat = bounds.minX
        var y: CGFloat = bounds.minY
        var lineHeight: CGFloat = 0

        for sub in subviews {
            let size = sub.sizeThatFits(.unspecified)
            if x + size.width > bounds.minX + maxWidth, x > bounds.minX {
                x = bounds.minX
                y += lineHeight + lineSpacing
                lineHeight = 0
            }
            sub.place(at: CGPoint(x: x, y: y), proposal: ProposedViewSize(size))
            x += size.width + spacing
            lineHeight = max(lineHeight, size.height)
        }
    }
}

// MARK: - Shimmer + Press style

private struct RowPressStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .scaleEffect(configuration.isPressed ? 0.985 : 1.0)
            .opacity(configuration.isPressed ? 0.92 : 1.0)
            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)
    }
}

private struct ShimmerOverlay: View {
    @State private var phase: CGFloat = -1

    var body: some View {
        GeometryReader { geo in
            LinearGradient(
                colors: [.white.opacity(0), .white.opacity(0.35), .white.opacity(0)],
                startPoint: .leading, endPoint: .trailing
            )
            .frame(width: geo.size.width * 0.6)
            .offset(x: phase * geo.size.width * 1.6)
            .blendMode(.plusLighter)
            .onAppear {
                withAnimation(.linear(duration: 1.2).repeatForever(autoreverses: false)) {
                    phase = 1.0
                }
            }
        }
        .allowsHitTesting(false)
    }
}

#Preview {
    ContentView(bearer: "019ec07a-c943-7275-b758-2315b8c9fa6f")
}
